---
plugins:
  - standard-performance
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - bin/*
  NewCops: enable

# comply with reek
Naming/RescuedExceptionsVariableName:
  Enabled: true
  PreferredName: error

# layout
Layout/LineLength:
  Enabled: true
  Max: 100

# metrics
Metrics/AbcSize:
  Enabled: true
  Max: 25
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
Metrics/ClassLength:
  Enabled: true
  # Max: 100
Metrics/ModuleLength:
  Enabled: true
  # Max: 200
# Metrics/MethodLength:
#   Max: 15
# Metrics/ParameterLists:
#   Enabled: true
#   Max: 4

# naming
Naming/PredicateName:
  Description: 'Check the names of predicate methods.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#bool-methods-qmark'
  ForbiddenPrefixes:
    - is_

# style
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes

